title: Sandra Lee
author: Sandra Lee
email: slee2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 Hello and welcome to my website. I will be presenting myself.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
