title: Sandra Lee
author: Sandra Lee
email: slee2@ebnet.orf
description: > # this means to ignore newlines until "baseurl:"
 Hello and welcome to my website. I will be presenting information about me. 

# social links
twitter_username: sandyleeks
github_username: sandralee23
instagram_username: sandra.lee_
discord_username: vitaminlee#4396

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
